---
services: 
    bookstack: 
    container_name: bookstack
    depends_on: 
        - bookstack_db
    environment: 
        - PUID=1000
        - PGID=1000
        - DB_HOST=bookstack_db
        - DB_USERNAME=bookstack
        - DB_PASSWORD=REDACTED
        - DB_DATABASE=bookstackapp
        - "APP_URL=https://not.real.com"
    image: linuxserver/bookstack
    ports: 
        - "6875:6875"
    restart: unless-stopped
    volumes: 
        - "/data/bookstack/bookstack_config:/config"
    bookstack_db: 
    container_name: bookstack_db
    environment: 
        - PUID=1000
        - PGID=1000
        - MYSQL_ROOT_PASSWORD=REDACTED
        - TZ=Europe/Brussels
        - MYSQL_DATABASE=bookstackapp
        - MYSQL_USER=bookstack
        - MYSQL_PASSWORD=REDACTED
    image: linuxserver/mariadb
    restart: unless-stopped
    volumes: 
        - "/data/bookstack/bookstack_db:/config"
volumes: 
    bookstack_config:
    bookstack_db: